### PR TITLE
[BLCKCHN-201] add 2nd ai call to generate final answer

### PR DESCRIPTION
**Pull request by leejw51crypto**
- consume one more ai api call to generate final answer 
- not to break protocol, add finalResponse
- use current context so far, maxium 10 messages (sliding window)
- modified clients : typescript, tgbot, python

### CODE REVIEW

**Comment by leejw51crypto** [comment]
add context to typescript, tg bot

**Comment by leejw51crypto** [comment]
resolving conflicts and tidy up

**Comment by leejw51crypto** [comment]
rebased

**Comment by leejw51crypto** [comment]
ok, i'll make a video

**Comment by rarcifa** [comment]
@leejw51crypto looks good. Do have bandwidth to update the cdc-agent-service to follow the same context sliding window?

**Comment by leejw51crypto** [comment]
cdc-agent-service  is stateless, currently client hold all context and sliding window

**Review by yeehan-crypto-com — APPROVED** [review]

**Pull request merged**
